### PR TITLE
Allow for nanosecond timestamps

### PR DESCRIPTION
**Pull request by pysysops**
Allow a UNIX_NANO format literal to handle timestamps which are in nanoseconds.

I have made this change as I am currently beta testing cloudflare's new logging API due for release at the end of Q1. All their times are in nanoseconds. 

I thought this may be useful to share this with the wider community in anticipation that people will probably want to consume into ELK from the CloudFlare API.

### CODE REVIEW

**Comment by pysysops** [comment]
I've just signed an individual contributor CLA. Thanks!

**Comment by untergeek** [comment]
The code and test look good.  I think there's a need to document that even if you provide nanoseconds, the resolution that comes out of the filter is still no more than milliseconds, and why.  I really wish JODA Time would allow nanoseconds, but it doesn't.

**Comment by untergeek** [comment]
The documentation should go after UNIX_MS: https://github.com/logstash-plugins/logstash-filter-date/blob/master/lib/logstash/filters/date.rb#L72

**Comment by untergeek** [comment]
I should mention that this is not just code documentation, but those bits are parsed out and become the online documentation. See https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html for reference.

**Comment by toog** [comment]
now Elasticsearch support date_nanos field. I think is necessary to implement this fucntionnality in logstash too.

**Pull request closed without merging**
