### PR TITLE
Release 2.1.5

### PR DESCRIPTION
**Pull request by wiibaa**
**Important:** Still waiting for final review and merge of #60

But hopefully this should not be long :) so let's get prepared

### CODE REVIEW

**Comment by suyograo** [comment]
@wiibaa rebase please? :)

**Comment by wiibaa** [comment]
@suyograo done also raised the version as the mass update come in between...

Also can you confirm that the **runtime** deps seems wrong and should be made development, @ph can you confirm please.

**Comment by suyograo** [comment]
LGTM

**Comment by ph** [comment]
@wiibaa I took a lot at the dependency from the gemspec.

From https://github.com/logstash-plugins/logstash-filter-date/blob/master/logstash-filter-date.gemspec#L23-L27

```ruby
  # current version
  s.add_runtime_dependency "logstash-core", ">= 2.0.0", "< 6.0.0.alpha1"
  s.add_runtime_dependency 'logstash-input-generator'
  s.add_runtime_dependency 'logstash-codec-json'
  s.add_runtime_dependency 'logstash-output-null'
  s.add_development_dependency 'logstash-devutils'
```
 'logstash-input-generator', logstash-codec-json' and 'logstash-output-null' should be marked as development not runtime.

Thanks for noticing it!

**Comment by wiibaa** [comment]
@ph @suyograo should I include this here or separate PR ?

**Comment by ph** [comment]
@wiibaa you can make it part of this PR, this is fine with me.

**Comment by wiibaa** [comment]
@ph @suyograo done!

**Comment by wiibaa** [comment]
@ph please ping me when it is safe to do the rebase :stuck_out_tongue_winking_eye:

**Comment by ph** [comment]
Its safe now sorry for the influx repository  :(

On Thu, Mar 24, 2016 at 7:40 AM, Philippe Weber <notifications@github.com>
wrote:

> @ph <https://github.com/ph> please ping me when it is safe to do the
> rebase [image: :stuck_out_tongue_winking_eye:]
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/logstash-plugins/logstash-filter-date/pull/61#issuecomment-200800105>
>



-- 
--
ph
Software Engineer

**Comment by wiibaa** [comment]
@suyograo @ph done again :)

**Comment by ph** [comment]
jenkins, test this please

**Comment by ph** [comment]
jenkins, test it

**Comment by ph** [comment]
please jenkins, test this

**Comment by ph** [comment]
Sorry for the noise, trying to make me jenkins like me

**Comment by ph** [comment]
@wiibaa Jenkins is a necessary pain sometime..

**Pull request closed without merging**
