### PR TITLE
test fix: update from TimeStamp#toIso8601 to Timestamp#toString and bump to JRuby 9k for compile 

### LINKED ISSUE #114: Test failure due to upstream removal of Timestamp.toIsoString
http://github.com/elastic/logstash/commit/d121c5818506fb1fba5203b8bcc14803a6c3a56c (https://github.com/elastic/logstash/pull/8130) removed an API that was used in this filter's tests.

### PR DESCRIPTION
**Pull request by jakelandis**
Fixes #114

Screen shot from the breaking upstream change (https://github.com/elastic/logstash/commit/d121c5818506fb1fba5203b8bcc14803a6c3a56c):

image

### CODE REVIEW

**Comment by jakelandis** [comment]
Now that this is fixed #116 is failing the build. Will fix that on this PR.

**Comment by jakelandis** [comment]
> I'm a little concerned with how fragile these tests are; they interact pretty directly into logstash-core objects, which means that implementation details of logstash-core are implicitly and pretty tightly bound to this plugin

@yaauie - yup, this is part of a much larger conversation about our plugin eco-system.

**Comment by jakelandis** [comment]
@yaauie - mind taking another look ?  I have included the fix for #116 too see [this](https://github.com/logstash-plugins/logstash-filter-date/issues/116#issuecomment-347659578) comment for additional context.

**Comment by jordansissel** [comment]
A major version bump means this plugin will not ship by default with Logstash until Logstash 7.0. The side effect is also that we will have to have two maintained branches (new major, current major) for all new features/bugfixes going forward until 7.0 ships.

Let's try really hard not to require a major version bump.

**Comment by jordansissel** [comment]
@jakelandis the [referenced upstream change](https://github.com/elastic/logstash/commit/d121c5818506fb1fba5203b8bcc14803a6c3a56c#diff-fa5ac2d3fc3cc5667de026b7e11dd217L61) doesn't remove or appear to change the behavior of `org.logstash.Timestamp.toString()`, it (to me, as I read it) removes toIso8601(). Since `toString` existed prior and after this patch with no (?) behavior change, I think this can be a patch-level version bump.

Thoughts?

**Comment by jakelandis** [comment]
@jordansissel - There are two changes here.  Both are needed to allow the build to pass (which is why i am making changes) 

#114 is patch level change 
#116 changes the compiled against version from JRuby 1.7 to JRuby 9k, and is the reason for the major version bump. 

There aren't actually any functional changes here, and no need to release these changes until something else comes along.  

It should be fine to include this major version bump in a minor version release of 6.x.  In hindsight, this change would have been made BEFORE 6.0 release since it is kinda risky (as evident by the test failures) to compile against different major versions of transitive dependencies.

**Comment by jordansissel** [comment]
We have traditionally aligned "semver" versioning against user experience and user interfaces of plugins. 

Here is the rubric I use for evaluating a version bump:

* Because the user interface is not breaking, this should not be a major version bump. 
* Because the user interface is not getting a new feature, this should not be minor version bump.
* Because we are fixing a bug, this should be a patch bump.

For compiling-with-jruby-9k -- are we using JRuby internals? From what I remember, JRuby is used as an execution engine to run the test suite from build.gradle. We don't use any JRuby classes directly in the java code. The only mention of jruby in src/main is this:

```
% rg -i jruby src/main
src/main/java/org/logstash/filters/DateFilter.java
26:import org.logstash.ext.JrubyEventExtLibrary.RubyEvent;
```

Do you think it will not work when executed under JRuby 1.7? We can test this manually by building the plugin from this PR and running it under Logstash 5.x.

**Comment by jakelandis** [comment]
>  Do you think it will not work when executed under JRuby 1.7? We can test this manually by building the plugin from this PR and running it under Logstash 5.x.

I did some manual testing  and it works, at least for my limited testing. 

> For compiling-with-jruby-9k -- are we using JRuby internals? 

Transitively, yes.  It is part of the class/method signatures that we compile against, and if those change between versions it can cause issues at runtime.  That applies to the entire dependency graph. 

> We have traditionally aligned "semver" versioning against user experience and user interfaces of plugins.

O.K. I can change it to a minor version.  However,  I am strongly against patch version since it should not be included to 5.x stream by default. I am not confident that the testing is verbose enough to catch this type of error.

**Comment by jakelandis** [comment]
Reduced to minor version (and fixed commit message)

@jordansissel - I will wait to merge for your thumbs up on the minor (instead of patch) version. 

@yaauie  - would you mind taking the rest of the review.

**Comment by jordansissel** [comment]
Jake I believe this is a bug. This plugin invokes org.logstash.Event.
Something internal to JRuby shouldn’t matter, should it? We don’t call
anything in JRuby. This has a bug smell to it, not something that is a
natural property of JRuby 9k

**Comment by jakelandis** [comment]
@jordansissel 

Simplest replication case of #116:

Let build.gradle JRuby version = 1.7.25 , but point gradle.properties to an Event / ConvertedMap class compiled with JRuby 9k for example: logstashCoreGemPath=/Users/jake/workspace/releases/logstash-6.0.0/logstash-core

```
@Test
public void test() throws Exception {
   new Event();
}
```

results in:


```
java.lang.NoClassDefFoundError: org/jruby/RubyHash$VisitorWithState

	at org.logstash.Event.<init>(Event.java:47)
	at org.logstash.filters.DateFilterTest.test(DateFilterTest.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.jruby.RubyHash$VisitorWithState
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
```

This happens when Event is compiled with JRuby 9k, but using JRuby 1.7 as the runtime:

new Event (constructor) -> ConvertedMap (constuctor) -> import org.jruby.RubyHash (from JRuby core) -> java.lang.NoClassDefFoundError: org/jruby/RubyHash$VisitorWithState 

JRuby 9k declares org.jruby.RubyHash$Visitor as:

```
public static abstract class Visitor extends VisitorWithState {
```

...but JRuby 1.7 declears org.jruby.RubyHash$Visitor as 

```
public static abstract class Visitor {
```

e.g. `VisitorWithState` is in JRuby9k, but is not part of JRuby 1.7

Since ConvertedMap imports org.jruby.RubyHash.Visitor and VisitorWithState is not on the class path (when JRuby 1.7 is the runtime), the error occurs. ...this is where the EXACT cause gets a bit foggy for me.

Inspecting the bytecode for the logstash 6.x cleary has references the class that does not exist on the class path. I am pretty sure that the JVM is actively trying to load all class references at time of import, and that is the root cause of the error. 

```
javap -classpath logstash-6.jar -v org.logstash.ConvertedMap | grep VisitorWithState
   #21 = Methodref          #84.#90       // org/jruby/RubyHash.visitAll:(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/RubyHash$VisitorWithState;Ljava/lang/Object;)V
   #90 = NameAndType        #122:#125     // visitAll:(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/RubyHash$VisitorWithState;Ljava/lang/Object;)V
  #123 = Class              #128          // org/jruby/RubyHash$VisitorWithState
  #124 = Utf8               VisitorWithState
  #125 = Utf8               (Lorg/jruby/runtime/ThreadContext;Lorg/jruby/RubyHash$VisitorWithState;Ljava/lang/Object;)V
  #128 = Utf8               org/jruby/RubyHash$VisitorWithState
        29: invokevirtual #21                 // Method org/jruby/RubyHash.visitAll:(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/RubyHash$VisitorWithState;Ljava/lang/Object;)V
     public static abstract #124= #123 of #84; //VisitorWithState=class org/jruby/RubyHash$VisitorWithState of class org/jruby/RubyHash
```

This means that anything compiled against JRuby 9k but run on with JRuby 1.7 is not guaranteed to work. (for at least this 1 case)

For this very specific example it appears that if compiled with JRuby 1.7 but run on JRuby 9k it will work. 

However, I highly doubt that JRuby would claim binary (backward or forward) compatibility for JRuby 1.7 or JRuby 9k. Even if they claim it, it would VERY hard to achieve. 

My point here is that there is risk when compiled against one version, but run against another. IMO we missed the opportunity to major version bump plugins when we upgraded to JRuby 9k as the runtime platform.  

Given that 6.0 ship has already already sailed, I am now advocating for minor version.

I agree (for the most part) with your version rubric, but specifically w/r/t to plugins vs. core versioning I propose a very simple model of major -> major, minor -> minor, and patch -> patch.  (I have a different discussion for formalizing this)

I *strongly* believe that this change should NOT be backported to 5.x to avoid the compile/runtime mismatch risk, hence my recommendation for minor and be included as part of the next 6.x minor release.

**Comment by jordansissel** [comment]
> 	at org.logstash.Event.<init>(Event.java:47)
>	at org.logstash.filters.DateFilterTest.test(DateFilterTest.java:145)

I'm still confused a bit.

The error happens in `org.logstash.Event` on an internal operation (new ConvertedMap). `Event` is an implementation provided at runtime by Logstash. I'm not sure how this is even occuring?

**Comment by jordansissel** [comment]
I will try to reproduce so I can work to find some understanding of how this fails. Sorry for my confusions here.

**Comment by jakelandis** [comment]
After discussing in person with @jordansissel we will move this down to a patch version bump. The reasons:
* There is no evidence to suggest it doesn't work on 5.x 
* There is evidence that it does indeed work on 5.x , manual and automated tests all pass against 5.x (JRuby 1.7) runtime
* The actual error here is a test only error and is caused by using parts of the API that production code does not use. 
* The JRuby dependency in this plugin is VERY minimal (by design) and is actually indirect via the core jar.

I will update the PR with the patch level change.

**Comment by jakelandis** [comment]
@yaauie  - can you look one more time ?  I bumped down to a patch version and included the other test fix in the change log. 
(sorry for the noise)

**Pull request closed without merging**
