### PR TITLE
Nanosecond timestamp support

### PR DESCRIPTION
**Pull request by pysysops**
Hi Guys,

Updated from a previous closed pull request. I have added documentation in the appropriate place and informed the user of the resulting millisecond accuracy.

Anything else that can be improved, I'd appreciate your feedback.

Thanks,
Tim.

### CODE REVIEW

**Comment by untergeek** [comment]
@pysysops I'm confused by the CLA check warning.  You said you signed an individual CLA, but according to this check it says you haven't.  Did you use the same email as the one associated with the @pysysops GitHub account?  This is what the CLA check tests.

**Comment by pysysops** [comment]
@untergeek - Darn it, thought it may have gone with the username. I've amended my Github account to the same email address as the CLA was signed with. Shall I resubmit the pull request? 

Thanks, Tim.

**Comment by untergeek** [comment]
That might not be a bad idea, just to see if it works.  When I check the database, I see your info (when looking up by github account id), and the email address maps to the lad bible domain.  But when I run our manual CLA check, it fails.

**Comment by pysysops** [comment]
Thanks @untergeek is the CLA update pretty much automated or does a CLA committer need to make a manual emndment somewhere? 

Also, before I resubmit... What would be your thoughts on me amending the UNIX_MS section of code to handle sub millisecond values and updating the documentation? I'm not sure I need to go adding new format literals when I can simply: date.to_s.slice(0..13).to_i and that will allow UNIX_MS to handle micro / nano seconds etc... without the need to support individual format literals for all cases. We already know that millisecond granularity is a limit of the Joda time api.

**Comment by untergeek** [comment]
@pysysops That's not a bad idea, actually.  Send it through and we'll review it as a team.

**Pull request closed without merging**
