### PR TITLE
Harmonize default date handling in different joda parsers

### PR DESCRIPTION
**Pull request by wiibaa**
There were a discrepancy within the lambda using joda-based parsers.
The main parsers contained all the logic for default year handling, but the secondary ones (sprintf timezone and en-fallback) did not.

This PR makes the 3 lambdas use the same logic and add tests for each secondary context

Fix for #58 and #57

### CODE REVIEW

**Comment by jsvd** [comment]
LGTM

**Comment by jsvd** [comment]
jenkins, test it

**Comment by wiibaa** [comment]
@jsvd sorry to have forgotten the version bump and changelog, I will prepare them.
In the meantime I would be in favor to get #27 in if possible as it is only doc

**Comment by jsvd** [comment]
no worries and, as you said, we should get the doc change in before the release anyway.

**Pull request closed without merging**
