### PR TITLE
Raising exception if UNIX timestamp is out of range

### PR DESCRIPTION
**Pull request by izhou99**
Fix as discussed in https://github.com/logstash-plugins/logstash-filter-date/pull/72

### CODE REVIEW

**Comment by karmi** [comment]
Hi @izhou99, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-filter-date/pull/73.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by izhou99** [comment]
@jordansissel can you take a look when you get a chance? Thanks!

**Comment by jordansissel** [comment]
LGTM

**Comment by jordansissel** [comment]
I'm in the process of rewriting this filter (#73) and will be sure to include your lovely patch in it :) Thank you!

**Comment by jordansissel** [comment]
As a note, I am pretty sure I kept this functionality in #74 (a major rewrite of the plugin) because your new specs are passing there. However, just in case, if you see weird unix+unix_ms behavior, please let me know and we will fix it asap.

<3

**Pull request closed without merging**
