### PR TITLE
Allow to read timezone from event

### PR DESCRIPTION
**Pull request by wiibaa**
Fix for #23   (and its duplicate #15)

### CODE REVIEW

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by purbon** [comment]
Hi @wiibaa, thanks a lot for your time and contribution. I'm sorry it took us too long to come here, we're really working hard to improve this. After taking a look at your code, might I miss read, but I can not see how this fix #24? I see it more as a fix for #15. What do you think?

Thanks!

**Comment by wiibaa** [comment]
@purbon you're right it was #23 , I fixed the desc

**Comment by purbon** [comment]
LGTM

**Comment by purbon** [comment]
Merged https://github.com/logstash-plugins/logstash-filter-date/commit/7e39e7775f8d802206c6b8cf778214af8bc8dbd0

**Pull request closed without merging**
